#kind: Namespace
#apiVersion: v1
#metadata:
#  name: cnm-server
#---
#kind: Deployment
#apiVersion: apps/v1
#metadata:
#  name: cnm-server
##  namespace: cnm-server
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: cnm-server
#  template:
#    metadata:
#      labels:
#        app: cnm-server
#    spec:
#      containers:
#        - name: cnm-server
#          image: narenrana02/cnm-retail_cnm_server
#          imagePullPolicy: Always
#          ports:
#            - containerPort: 8580
#      restartPolicy: Always
#---
#kind: Service
#apiVersion: v1
#metadata:
#  name: cnm-server
##  namespace: cnm-server
#spec:
#  type: LoadBalancer
#  ports:
#    - port: 8580
#      targetPort: 8580
##      protocol: TCP
##      nodePort: 31000
#  selector:
#    app: cnm-server