version: '3.5'
services:
  cnm_server:
    container_name: cnm_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: "on-failure"
    depends_on:
      postgres:
        condition: service_healthy
  main_app:
    container_name: main_app
    build:
      context: .
      dockerfile: ./cnm-app/Dockerfile
    volumes:
      - '.:/cnm-app'
    ports:
      - "3000:3000"
    restart: "on-failure"
    networks:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
  cnm_payment:
    container_name: cnm_payment
    build:
      context: .
      dockerfile: ./payment-app/Dockerfile
    volumes:
      - '.:/cnm-app'
    ports:
      - "3001:3000"
    restart: "on-failure"
    networks:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: