package constants


const (
        COMBO_OFFER  ="COMBO_OFFER"
        INDIVIDUAL_ITEM_OFFER = "INDIVIDUAL_ITEM_OFFER"
        CHRISTMAS_OFFER = "CHRISTMAS_OFFER"
        NEW_YEAR_OFFER="NEW_YEAR_OFFER"
        BLACK_FRIDAY_OFFER="BLACK_FRIDAY"
)
