kind: Deployment
apiVersion: apps/v1
metadata:
  name: main-app
  namespace: app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
        - name: main-app
          image: narenrana02/cnm-retail_main_app
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: main-app
  namespace: app
#  namespace: main-app
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
#      protocol: TCP
#      nodePort: 31000
  selector:
    app: main-app